const notFoundError = (res) => {
  return res.status(404).send("Este dado n√£o foi encontrado!");
};

module.exports = {
  notFoundError,
};
